CREATE TYPE "public"."content_type" AS ENUM('blog_post', 'social_post', 'video', 'infographic', 'newsletter', 'podcast', 'case_study', 'webinar', 'product_update', 'press_release', 'how_to_guide', 'interview', 'review', 'other');--> statement-breakpoint
CREATE TYPE "public"."platform_type" AS ENUM('website', 'blog', 'twitter', 'linkedin', 'instagram', 'tiktok', 'youtube', 'facebook', 'medium', 'email', 'other');--> statement-breakpoint
CREATE TYPE "public"."processing_status" AS ENUM('pending', 'processing', 'completed', 'failed');--> statement-breakpoint
CREATE TABLE "contently_analyzed_url" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_analyzed_url_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url" varchar(2048) NOT NULL,
	"status" "processing_status" DEFAULT 'pending' NOT NULL,
	"error_message" text,
	"user_id" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "contently_content_analytics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_content_analytics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"analyzed_url_id" integer NOT NULL,
	"engagement_score" integer NOT NULL,
	"engagement_explanation" text,
	"content_quality_score" integer NOT NULL,
	"content_quality_explanation" text,
	"readability_score" integer NOT NULL,
	"readability_explanation" text,
	"seo_score" integer NOT NULL,
	"seo_explanation" text,
	"industry" varchar(100) DEFAULT 'General' NOT NULL,
	"industry_explanation" text,
	"scope" varchar(50) DEFAULT 'General' NOT NULL,
	"scope_explanation" text,
	"topics" json DEFAULT '[]'::json NOT NULL,
	"topics_explanation" text,
	"writing_quality" json NOT NULL,
	"audience_level" varchar(50) DEFAULT 'General' NOT NULL,
	"audience_level_explanation" text,
	"content_type" varchar(100) DEFAULT 'Article' NOT NULL,
	"content_type_explanation" text,
	"tone" varchar(50) DEFAULT 'Neutral' NOT NULL,
	"tone_explanation" text,
	"estimated_read_time" integer DEFAULT 0 NOT NULL,
	"keywords" json DEFAULT '[]'::json NOT NULL,
	"keyword_analysis" json NOT NULL,
	"insights" json NOT NULL,
	"word_count_stats" json NOT NULL,
	"articles_per_month" json DEFAULT '[]'::json NOT NULL,
	"engagement" json NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "contently_content_calendar_suggestion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_content_calendar_suggestion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256),
	"title" varchar(256) NOT NULL,
	"content_type" "content_type" NOT NULL,
	"platform" "platform_type" NOT NULL,
	"topic" varchar(256) NOT NULL,
	"suggested_date" timestamp with time zone NOT NULL,
	"suggested_time" varchar(50) NOT NULL,
	"description" text,
	"rationale" text NOT NULL,
	"predicted_engagement" integer NOT NULL,
	"source_analytics_ids" json NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "contently_content_performance_metric" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_content_performance_metric_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256),
	"topic" varchar(256) NOT NULL,
	"content_type" "content_type" NOT NULL,
	"platform" "platform_type" NOT NULL,
	"engagement_rate" integer NOT NULL,
	"click_through_rate" integer,
	"conversion_rate" integer,
	"best_time_of_day" varchar(50),
	"best_day_of_week" integer,
	"audience_segment" varchar(100),
	"data_points" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "contently_optimal_posting_time" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_optimal_posting_time_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(256),
	"platform" "platform_type" NOT NULL,
	"day_of_week" integer NOT NULL,
	"time_of_day" varchar(50) NOT NULL,
	"engagement_score" integer NOT NULL,
	"confidence_level" integer NOT NULL,
	"data_points" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "contently_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "contently_url_content" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_url_content_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"analyzed_url_id" integer NOT NULL,
	"headings" json,
	"links" json,
	"images" json,
	"tables" json,
	"structured_data" json,
	"main_content" text,
	"screenshot" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contently_url_metadata" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contently_url_metadata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"analyzed_url_id" integer NOT NULL,
	"title" text,
	"description" text,
	"keywords" text,
	"author" varchar(256),
	"og_image" varchar(2048),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "contently_content_analytics" ADD CONSTRAINT "contently_content_analytics_analyzed_url_id_contently_analyzed_url_id_fk" FOREIGN KEY ("analyzed_url_id") REFERENCES "public"."contently_analyzed_url"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contently_url_content" ADD CONSTRAINT "contently_url_content_analyzed_url_id_contently_analyzed_url_id_fk" FOREIGN KEY ("analyzed_url_id") REFERENCES "public"."contently_analyzed_url"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contently_url_metadata" ADD CONSTRAINT "contently_url_metadata_analyzed_url_id_contently_analyzed_url_id_fk" FOREIGN KEY ("analyzed_url_id") REFERENCES "public"."contently_analyzed_url"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "url_idx" ON "contently_analyzed_url" USING btree ("url");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "contently_analyzed_url" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "status_idx" ON "contently_analyzed_url" USING btree ("status");--> statement-breakpoint
CREATE INDEX "analytics_analyzed_url_id_idx" ON "contently_content_analytics" USING btree ("analyzed_url_id");--> statement-breakpoint
CREATE INDEX "calendar_user_id_idx" ON "contently_content_calendar_suggestion" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "calendar_platform_idx" ON "contently_content_calendar_suggestion" USING btree ("platform");--> statement-breakpoint
CREATE INDEX "calendar_content_type_idx" ON "contently_content_calendar_suggestion" USING btree ("content_type");--> statement-breakpoint
CREATE INDEX "calendar_suggested_date_idx" ON "contently_content_calendar_suggestion" USING btree ("suggested_date");--> statement-breakpoint
CREATE INDEX "performance_user_id_idx" ON "contently_content_performance_metric" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "performance_topic_idx" ON "contently_content_performance_metric" USING btree ("topic");--> statement-breakpoint
CREATE INDEX "performance_platform_idx" ON "contently_content_performance_metric" USING btree ("platform");--> statement-breakpoint
CREATE INDEX "performance_content_type_idx" ON "contently_content_performance_metric" USING btree ("content_type");--> statement-breakpoint
CREATE INDEX "optimal_time_user_id_idx" ON "contently_optimal_posting_time" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "optimal_time_platform_idx" ON "contently_optimal_posting_time" USING btree ("platform");--> statement-breakpoint
CREATE INDEX "optimal_time_day_time_idx" ON "contently_optimal_posting_time" USING btree ("day_of_week","time_of_day");--> statement-breakpoint
CREATE INDEX "name_idx" ON "contently_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "content_analyzed_url_id_idx" ON "contently_url_content" USING btree ("analyzed_url_id");--> statement-breakpoint
CREATE INDEX "analyzed_url_id_idx" ON "contently_url_metadata" USING btree ("analyzed_url_id");